#!/bin/bash

python3 execute.py rtsp://admin:Oncorhynchus@192.168.1.230:554/h264Preview_01_sub models/megadetector.pt 0.85 0 livingRoom -99.99999 -99.99999 ./outfile/ --output_with_bounding_boxes yes
